void testDynamicArrayAll();
void testLinkedListAll();
void testArraySequenceAll();
void testListSequenceAll();
void testMutableAll();
void testImmutableAll();
void testBitSequenceAll();
void testICollectionAll();
void testStackAll();
void testQueueAll();
void testDequeAll();
void testHanoiAll();
void testBinaryHeapAll();
void testFixedQueueAll();
void testOrdinalAll();
void testGeneratorAll();
void testLazySequenceAll();
void testStreamsAll();
void testOnlineStatsAll();
void testStreamSorterAll();

int main() {
    testDynamicArrayAll();
    testLinkedListAll();
    testArraySequenceAll();
    testListSequenceAll();
    testMutableAll();
    testImmutableAll();
    testBitSequenceAll();
    testICollectionAll();
    testStackAll();
    testQueueAll();
    testDequeAll();
    testHanoiAll();
    testBinaryHeapAll();
    testFixedQueueAll();
    testOrdinalAll();
    testGeneratorAll();
    testLazySequenceAll();
    testStreamsAll();
    testOnlineStatsAll();
    testStreamSorterAll();
}
